# Generated by Django 3.2.13 on 2022-04-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionstoreuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
