# Generated by Django 3.2.13 on 2022-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220412_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(max_length=300),
        ),
    ]
