# Generated by Django 3.2.13 on 2022-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_picture', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
